# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

class TestLoginCorrecto():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginCorrecto(self):
    self.driver.get("http://localhost:3001/login")
    self.driver.set_window_size(974, 1032)
    self.driver.find_element(By.ID, "input_email").click()
    self.driver.find_element(By.ID, "input_email").send_keys("sebastian.cerna@pucp.edu.pe")
    self.driver.find_element(By.ID, "input_password").click()
    self.driver.find_element(By.ID, "input_password").send_keys("edumentor1234")
    self.driver.find_element(By.ID, "button_iniciar_sesion").click()
    WebDriverWait(self.driver, 1).until(EC.url_to_be("http://localhost:3001/seleccionar"))
    assert self.driver.current_url == "http://localhost:3001/seleccionar"
  
